# Generated by Django 5.0.5 on 2024-05-07 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Books_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('year', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='rasm/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.books_category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=128)),
                ('star_given', models.IntegerField()),
                ('user', models.CharField(max_length=128)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.books')),
            ],
        ),
    ]
